Fish 8992 run activation tck
payara/jakartaee-10-tck-runners pull request #63
Opened 2024-07-22 13:44 UTC by luiseufrasio

The build finishes with success, but it seems that no ant tests are found

2024-07-23 15:31 UTC, Pandrex247 requested changes

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +        </dependency>
Defined in parent pom `payara-server-managed` profile
```suggestion
```

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +        <payara.home>${project.build.directory}/payara7</payara.home>
Defined in parent pom
```suggestion
```

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +            </plugin>
Unpacking Payara defined in `payara-server-managed` profile
```suggestion
            <!-- Unpack TCK -->
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <skip>${skipTests}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>unpack-tck</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>jakarta-activation-tck</includeArtifactIds>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +                    <skip>${skipITs}</skip>
```suggestion
                    <skip>${skipTests}</skip>
```

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +                    <skip>${skipITs}</skip>
```suggestion
                    <skip>${skipTests}</skip>
```

2024-07-23 15:31 UTC, Pandrex247 commented on activation-tck/pom.xml
> +                    <skip>${skipITs}</skip>
```suggestion
                    <skip>${skipTests}</skip>
```

2024-07-30 22:02 UTC, breakponchito commented
@luiseufrasio please review comments added by @Pandrex247

2024-08-05 08:42 UTC, Pandrex247 approved these changes

2024-08-05 08:47 UTC, merged